name: Pre-Terraform Routine for Auth
description: "Shared routines used for authenticating to certain providers, modules or backends"

inputs:
  aws__access-key-id:
    description: "The AWS access key ID used for authentication in API requests."
  aws__secret-access-key:
    description: "The AWS secret access key associated with the access key ID for secure authentication."
  aws__oidc-arn:
    description: "The Amazon Resource Name (ARN) of the AWS OIDC role assigned to the GitHub OIDC provider for authentication."
  aws__region:
    description: "The target AWS region where Terraform resources will be provisioned."
  hcp__api-token:
    description: "The API token for HashiCorp Cloud Platform (HCP) Terraform, granting access to team-level operations."
  hcp__tf-version:
    description: "The specific Terraform version to install and use during the job execution."
    default: '1.11.3'
    
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials (OIDC)
      if: ${{ inputs.aws__oidc-arn != '' && inputs.aws__region != '' }}
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws__oidc-arn }}
        aws-region: ${{ inputs.aws__region }}

    - name: Configure AWS credentials (Static IAM)
      if: ${{ inputs.aws__secret-access-key != '' && inputs.aws__access-key-id != '' }}
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws__access-key-id }}
        aws-secret-access-key: ${{ inputs.aws__secret-access-key }}
        aws-region: ${{ inputs.aws__region }}
        
    - name: Setup Terraform with HCP Remote Cloud
      if: ${{ inputs.hcp__api-token != ''}}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.hcp__tf-version }}
        cli_config_credentials_token: ${{ inputs.hcp__api-token }}

    - name: Setup Terraform locally
      if: ${{ inputs.hcp__api-token == ''}}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.hcp__tf-version }}
    
