name: "Azure Terraform Authentication"
description: "Emergency authentication using personal Azure account"

inputs:
  ARM_CLIENT_ID:
    description: "Azure Client ID"
    required: false
  ARM_CLIENT_SECRET:
    description: "Azure Client Secret"  
    required: false
  ARM_TENANT_ID:
    description: "Azure Tenant ID"
    required: true
  ARM_SUBSCRIPTION_ID:
    description: "Azure Subscription ID"
    required: true
  terraform__version:
    description: "Terraform version"
    default: '1.6.6'
    
runs:
  using: composite
  steps:
    - name: Emergency Authentication Setup
      shell: bash
      run: |
        echo "🚨 Using emergency authentication mode"
        echo "⚠️  This uses GitHub runner with Azure CLI"
        
        # GitHub runners come with Azure CLI pre-installed
        az version
        
        # Set subscription context
        az account set --subscription ${{ inputs.ARM_SUBSCRIPTION_ID }}
        
        echo "✅ Emergency authentication configured"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform__version }}

    - name: Set Terraform Environment Variables
      shell: bash
      run: |
        echo "ARM_TENANT_ID=${{ inputs.ARM_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_CLI=true" >> $GITHUB_ENV
        echo "✅ Terraform configured for CLI authentication"
