name: "Emergency Azure Auth"
description: "Simple emergency authentication"

inputs:
  ARM_TENANT_ID:
    description: "Azure Tenant ID"
    required: true
  ARM_SUBSCRIPTION_ID:
    description: "Azure Subscription ID"  
    required: true
  terraform__version:
    description: "Terraform version"
    default: '1.6.6'
    
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform__version }}

    - name: Disable Terraform Cloud
      shell: bash
      run: |
        echo "Disabling Terraform Cloud..."
        rm -f ~/.terraformrc 2>/dev/null || true
        rm -f ~/.terraform.d/credentials.tfrc.json 2>/dev/null || true
        mkdir -p ~/.terraform.d
        echo '{}' > ~/.terraform.d/credentials.tfrc.json

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "ARM_TENANT_ID=${{ inputs.ARM_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_CLI=true" >> $GITHUB_ENV
        echo "TF_INPUT=false" >> $GITHUB_ENV
        echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV

    - name: Test Azure Access
      shell: bash
      run: |
        az version || echo "Azure CLI not available"
        az account show 2>/dev/null || echo "No Azure session - will use environment variables"
