name: "Azure Terraform Authentication"
description: |
  Centralized authentication for Azure with OIDC support and Azure Key Vault integration.
  Supports local backend (no HCP cloud dependency).

inputs:
  # Azure OIDC Configuration
  azure__client-id:
    description: "Azure Client ID for OIDC authentication"
    required: false
  azure__tenant-id:
    description: "Azure Tenant ID for OIDC authentication"  
    required: false
  azure__subscription-id:
    description: "Azure Subscription ID for OIDC authentication"
    required: false
  
  # Legacy Support
  ARM_CLIENT_ID:
    description: "Azure Client ID for service principal"
    required: false
  ARM_CLIENT_SECRET:
    description: "Azure Client Secret for service principal"
    required: false
  ARM_TENANT_ID:
    description: "Azure Tenant ID"
    required: false
  ARM_SUBSCRIPTION_ID:
    description: "Azure Subscription ID"
    required: false
  
  # Terraform Configuration
  terraform__version:
    description: "Terraform version to install"
    default: '1.6.6'
    
runs:
  using: composite
  steps:
    - name: Configure Azure Credentials (OIDC)
      if: ${{ inputs.azure__client-id != '' && inputs.azure__tenant-id != '' }}
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure__client-id }}
        tenant-id: ${{ inputs.azure__tenant-id }}
        subscription-id: ${{ inputs.azure__subscription-id }}
        enable-AzPSSession: true

    - name: Configure Azure Credentials (Service Principal)
      if: ${{ inputs.ARM_CLIENT_ID != '' && inputs.ARM_CLIENT_SECRET != '' }}
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ inputs.ARM_CLIENT_ID }}","clientSecret":"${{ inputs.ARM_CLIENT_SECRET }}","subscriptionId":"${{ inputs.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ inputs.ARM_TENANT_ID }}"}'
        enable-AzPSSession: true

    - name: Setup Terraform (Local Backend)
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform__version }}

    - name: Install Azure CLI Extensions
      shell: bash
      run: |
        az extension add --name application-gateway --only-show-errors || true
        az extension add --name aks-preview --only-show-errors || true
        
    - name: Set Azure Environment Variables
      shell: bash
      run: |
        if [ -n "${{ inputs.azure__client-id }}" ]; then
          echo "ARM_CLIENT_ID=${{ inputs.azure__client-id }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ inputs.azure__tenant-id }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ inputs.azure__subscription-id }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
        elif [ -n "${{ inputs.ARM_CLIENT_ID }}" ]; then
          echo "ARM_CLIENT_ID=${{ inputs.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ inputs.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ inputs.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ inputs.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        fi
